### ISSUE TITLE
Color from Colorcode isn't applied in lore

### ISSUE THREAD

**Issue by LoJoSho** [Auxilor/StatTrackers#11]
**Describe the bug**
When in item lore, the color isn't applied to the item. This causes this: https://i.imgur.com/ZRDfiFV.png

**To Reproduce**

Apply a tracker on an item, look at the lore. 

**Expected behavior**
The color lore should change into the color.

**Screenshots**

Screenshot provided above.

**Server Information (please complete the following information):**
- Version: 4.2.3
- Eco Version: 6.21.1

**Additional context**

Visual Bug doesn't appear to affect the actual tracking. 

Config: https://hastebin.de/itotewicir.yaml

**Comment by knniDE** [comment]
unfortunately, this bug has existed for some time. _OfTeN_ (Support Stuff) has fixed this problem for me.
On the Discord server several users already had this problem.
Therefore use the following version of OfTeN: 
https://cdn.discordapp.com/attachments/786310397190733854/931442641315430490/StatTrackers_v4.2.3.jar

**Comment by WillFP** [comment]
Fixed in latest
