### ISSUE TITLE
Trackers disappear

### ISSUE THREAD

**Issue by ZConnorZ** [Auxilor/StatTrackers#16]
**Describe the bug**
Trackers disappear

**To Reproduce**
1. Put trackers in gui /stattracker
2. Close the gui.
3. Open the stattracker gui and do not touch the trackers.
4. Close and then open gui, trackers will disappear.

**Server Information (please complete the following information):**
- Version:Current: git-Purpur-1561 (MC: 1.18.1)
- Version of plugin: 5.0.5.
- Version eco: 6.34.0

**Additional context**
In the gui, you can put something other than a tracker. It would be nice to ban it.

**Comment by ZConnorZ** [comment]
@WillFP

**Comment by ZConnorZ** [comment]
cry

**Comment by Yunuskrn** [comment]
same thing happened to me 2

**Comment by WillFP** [comment]
Fixed
