### ISSUE TITLE
Tracker Items Do Not Apply Stats To Items Dropped On

### ISSUE THREAD

**Issue by Kalikars** [Auxilor/StatTrackers#2]
**Issue:** Stat Tracker compasses do not apply stat tracking to items when dropped on them.

**Steps to Reproduce:** Use either /stattrackers:stgive <player> damage_dealt or craft a stat-tracker to acquire a compass. Drop a sword or other tool onto the ground and drop the compass on top of it. The compass and the sword/tool will stay seperate and will not merge.

**Screenshots:** [Imgur album showing steps listed above.](https://imgur.com/a/98RMKAW)

Running on Spigot 1.16.5, version 2991-Spigot-018b9a0-f3f3094 (Implementing API version 1.16.5-R0.1-SNAPSHOT). Using these plugins: LuckPerms, Lasso, Universes, Trash, KuthsBookExchange, EditableSign, CommandToItem, HeadDatabase, F3NPerm, MyCommand, **ProtocolLib, eco, StatTrackers**

**Comment by WillFP** [comment]
Doesn't work in creative mode, there are inventory bugs in the game

**Comment by Kalikars** [comment]
Doesn't seem to work in survival mode either.
